### ISSUE TITLE
I am unable to login with Admin User

### ISSUE THREAD

**Issue by anildalar** [pchero/jade#242]
https://37b4-2a01-4f9-5a-1303-00-2.ngrok-free.app/#/login

I am entering credential
username: admin
password: admin

When i click on login it failed with Request Timeout Error
Let me know what i am doing wrong?

![WhatsApp Image 2024-05-26 at 12 11 27 PM](https://github.com/pchero/jade/assets/25725857/d2e852f0-55ba-4293-a373-f840f673f501)

**Comment by pchero** [comment]
Hi Anildalar,

Unfortunately, the jade project is no longer in maintenance. Most of features are moved to the new project - voipbin.

Please check out the voipbin project here.

* http://voipbin.net/

Thank you.

Kind regards,
Sungtae

**Comment by anildalar** [comment]
Ok thanks for reply
