### ISSUE TITLE
other databases

### ISSUE THREAD

**Issue by ernany** [pchero/jade#82]
do you want to add other databases?

**Comment by pchero** [comment]
Hi ernany, 

Thank you for open the issue. 

For the new database, I have a plan for that in the future, but not now. :)

**Comment by ernany** [comment]
Congratulations on the project, I will study and contribute when I have some time.

**Comment by pchero** [comment]
Sure! :)

Thank you for having interested in. :)
I'll close issue at this point. But please feel free to reopen or recreate one.
